name: Build Zygisk Dump Dex      # CI 名称

on:
  push:
    branches: [main]             # 推到 main 自动跑
  pull_request:                  # PR 也跑
  workflow_dispatch:             # 允许网页手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project

    steps:
      # ① 拉代码
      - uses: actions/checkout@v4

      # ② 固定到 1.87 时期 nightly  ───★ 只看这一行 ★───
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2024-05-20    # ★ 必须 < 2024-06-26
          target: aarch64-linux-android
          override: true

      # ③ 安装构建工具
      - run: cargo install just --locked
      - run: cargo install cargo-ndk --locked

      # ④ 编译 & 打包 ZIP
      - run: just package-release          # 仓库自带 justfile

      # ⑤ 上传产物（保留 90 天）
      - uses: actions/upload-artifact@v4
        with:
          name: zygisk-debug-zip
          path: out/zygisk-*.zip
          compression-level: 9
          retention-days: 90
